apiVersion: apps/v1
kind: Deployment
metadata:
  name: archie-proxy-deployment
spec:
  selector:
    matchLabels:
      app: archie-proxy
  replicas: 1
  template:
    metadata:
      labels:
        app: archie-proxy
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        volumeMounts:
          - name: archie-proxy-config
            mountPath: /etc/nginx/nginx.conf
            subPath: nginx.conf
      volumes:
      - name: archie-proxy-config
        configMap:
          name: archie-proxy-nginx-config
---
apiVersion: v1
kind: Service
metadata:
  name: archie-proxy-service
spec:
  selector:
    app: archie-proxy
  ports:
  - name: web
    port: 80
    targetPort: 80
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: archie-proxy-ingress
  annotations:
    kubernetes.io/ingress.class: "traefik"
    kubernetes.io/tls-acme: "true"
    traefik.ingress.kubernetes.io/redirect-entry-point: https
    traefik.ingress.kubernetes.io/rate-limit: |
      extractorfunc: client.ip
      rateset:
        api-rateset:
          period: 5s
          average: 100
          burst: 50
spec:
  rules:
  - host: archie-proxy.xl4d.xyz
    http:
      paths:
      - path: /
        backend:
          serviceName: archie-proxy-service
          servicePort: 80
  tls:
  - hosts:
    - 'archie-proxy.xl4d.xyz'
