
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hass-deployment
spec:
  selector:
    matchLabels:
      app: hass
  replicas: 1
  template:
    metadata:
      labels:
        app: hass
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        volumeMounts:
          - name: hass-config
            mountPath: /etc/nginx/nginx.conf
            subPath: nginx.conf
      volumes:
      - name: hass-config
        configMap:
          name: hass-nginx-config
---
apiVersion: v1
kind: Service
metadata:
  name: hass-service
spec:
  selector:
    app: hass
  ports:
  - name: web
    port: 80
    targetPort: 80
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: hass-ingress
  annotations:
    kubernetes.io/ingress.class: "traefik"
    kubernetes.io/tls-acme: "true"
    traefik.ingress.kubernetes.io/redirect-entry-point: https
spec:
  rules:
  - host: hass.xl4d.xyz
    http:
      paths:
      - path: /
        backend:
          serviceName: hass-service
          servicePort: 80
  tls:
  - hosts:
      - 'hass.xl4d.xyz'
